

spring:
  thymeleaf:
    cache: false
    servlet:
      produce-partial-output-while-processing: true
    enable-spring-el-compiler: true

  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/library}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:fossil}