logging:
  file:
    name: logs/library.log
  level:
    ROOT: WARN
    org.springframework: ERROR
    com.mikebryant: DEBUG

spring.output.ansi.enabled: detect

server:
  port: 8080
  servlet:
    context-path: /lodgelibrary

file:
  image:
    location: /opt/rednour/fileuploads/

spring:
  thymeleaf:
    cache: true
    servlet:
      produce-partial-output-while-processing: true
    enable-spring-el-compiler: true

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

    hikari:
      login-timeout: 2500
      initialization-fail-timeout: 2500
      maximum-pool-size: 2
      auto-commit: true
      idle-timeout: 60000
      minimum-idle: 1

  jpa:
    properties:
      show-sql: true
