logging:
  file:
    name: logs/library.log
  level:
    ROOT: WARN
    org.springframework: ERROR
    com.mikebryant: DEBUG

spring.output.ansi.enabled: detect

server:
  port: 8080

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/library}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:fossil}

    hikari:
      login-timeout: 2500
      initialization-fail-timeout: 2500
      maximum-pool-size: 2
      auto-commit: true
      idle-timeout: 60000
      minimum-idle: 1

  jpa:
    properties:
      show-sql: true

